name: generate-pacman

on:
  schedule:
    - cron: "0 */6 * * *"   # jalan tiap 6 jam sekali
  workflow_dispatch:        # bisa dijalankan manual di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate pacman
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif
            dist/github-snake-dark.gif?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
